### ISSUE TITLE
 English Translation

### ISSUE THREAD

**Issue by cdprf** [hanc00l/nemo_go#81]
First of all, I want to thank you for your amazing project. I've been trying to test it and managed to overcome a few issues. However, I'm facing difficulties with the language, as I do not understand Chinese. Both the web interface and the documentation are in Chinese, and it would be great to have them available in English.

I was wondering if you have plans to translate the web interface and documentation into English, and if so, do you have an estimated timeline for this? It would be beneficial for a broader audience to understand and use your project.

If you need any assistance with the translation, I would be more than happy to contribute and help with the English version.

Thank you in advance for your response, and I'm looking forward to any updates on this matter.

Best regards,

**Comment by hanc00l** [comment]
Glad that you pay attention to my project and make good suggestions.

This project is an open source project outside of personal work. Due to personal ability and energy and other reasons, the project cannot be too professional and meet the various needs of network security researchers. In the back-end golang code, I will try to use English later to make it easier for everyone to read and understand; I am not good at the front-end page, so it is not easy to change it to support international multi-language, please forgive me.

The original intention of open source code is also to improve and improve the project together with interested network security researchers, and also hope that more enthusiasts can participate together.

Thanks.
